export const mockRules = [
    {
        id: "1",
        name: "Container Workload Protection",
        type: "elastic",
        riskScore: 47,
        severity: "Medium",
        lastRun: "3 minutes ago",
        lastResponse: "Warning",
        lastUpdated: "2 hours ago",
        enabled: true,
        integrations: "0/1 integrations",
        tags: ["Data Source: Active Directory", "Data Source: Amazon EC2"],
        category: "Container",
        ruleType:"HIDS"
    },
    {
        id: "2",
        name: "Endpoint Security",
        type: "elastic",
        riskScore: 47,
        severity: "Medium",
        lastRun: "3 minutes ago",
        lastResponse: "Warning",
        lastUpdated: "2 hours ago",
        enabled: true,
        integrations: "0/1 integrations",
        tags: ["Data Source: Active Directory"],
        category: "Endpoint",
        ruleType:"NIDS"
    },
    {
        id: "3",
        name: "Halfbaked Command and Control Beacon",
        type: "elastic",
        riskScore: 73,
        severity: "High",
        lastRun: null,
        lastResponse: null,
        lastUpdated: "2 hours ago",
        enabled: false,
        integrations: "0/5 integrations",
        tags: ["Data Source: Active Directory", "Data Source: Amazon EC2", "Data Source: Amazon Web Services"],
        category: "Halfbaked",
        ruleType:"HIDS"
    },
    {
        id: "4",
        name: "Creation of a Hidden Local User Account",
        type: "elastic",
        riskScore: 73,
        severity: "High",
        lastRun: null,
        lastResponse: null,
        lastUpdated: "2 hours ago",
        enabled: false,
        integrations: "0/2 integrations",
        tags: ["Data Source: Active Directory", "Data Source: Amazon EC2", "Data Source: Amazon Web Services", "Data Source: APM"],
        category: "Creation",
        ruleType:"HIDS"
    },
    {
        id: "5",
        name: "PowerShell Suspicious Script with Audio Capture Capability",
        type: "elastic",
        riskScore: 47,
        severity: "Medium",
        lastRun: null,
        lastResponse: null,
        lastUpdated: "2 hours ago",
        enabled: false,
        integrations: "0/1 integrations",
        tags: ["Data Source: Active Directory", "Data Source: Amazon EC2", "Data Source: Amazon Web Services", "Data Source: APM"],
        category: "PowerShell",
    },
    {
        id: "6",
        name: "Windows Defender Disabled via Registry Modification",
        type: "elastic",
        riskScore: 21,
        severity: "Low",
        lastRun: null,
        lastResponse: null,
        lastUpdated: "2 hours ago",
        enabled: false,
        integrations: "0/3 integrations",
        tags: ["Data Source: Active Directory"],
        category: "Windows Defender",
    },
    {
        id: "7",
        name: "Startup Folder Persistence via Unsigned Process",
        type: "elastic",
        riskScore: 47,
        severity: "Medium",
        lastRun: null,
        lastResponse: null,
        lastUpdated: "2 hours ago",
        enabled: false,
        integrations: "0/1 integrations",
        tags: ["Data Source: Active Directory", "Data Source: APM"],
        category: "Startup Folder Persistence",
    },
    {
        id: "8",
        name: "GCP Firewall Rule Creation",
        type: "elastic",
        riskScore: 21,
        severity: "Low",
        lastRun: null,
        lastResponse: null,
        lastUpdated: "2 hours ago",
        enabled: false,
        integrations: "0/1 integrations",
        tags: ["Data Source: APM"],
        category: "GCP Firewall",
    },
    {
        id: "9",
        name: "AWS S3 Object Versioning Suspended",
        type: "elastic",
        riskScore: 47,
        severity: "Medium",
        lastRun: null,
        lastResponse: null,
        lastUpdated: "2 hours ago",
        enabled: false,
        integrations: "0/1 integrations",
        tags: ["Data Source: Active Directory", "Data Source: Amazon Web Services", "Data Source: APM"],
        category: "AWS S3 Object",
    },
    {
        id: "10",
        name: "Inbound Connection to an Unsecure Elasticsearch Node",
        type: "elastic",
        riskScore: 47,
        severity: "Medium",
        lastRun: null,
        lastResponse: null,
        lastUpdated: "2 hours ago",
        enabled: false,
        integrations: "3",
        tags: ["Data Source: Active Directory"],
        category: "Inbound Connection",
    },
    // Add more mock rules to demonstrate pagination
    ...Array.from({ length: 960 }, (_, i) => ({
        id: `${i + 11}`,
        name: `Security Rule ${i + 11}`,
        type: i % 5 === 0 ? "custom" : "elastic",
        riskScore: [21, 47, 73][Math.floor(Math.random() * 3)],
        severity: ["Low", "Medium", "High"][Math.floor(Math.random() * 3)],
        lastRun: i % 4 === 0 ? "5 minutes ago" : null,
        lastResponse: i % 4 === 0 ? "Warning" : null,
        lastUpdated: "2 hours ago",
        enabled: i % 3 === 0,
        integrations: i % 2 === 0 ? `0/${Math.floor(Math.random() * 3) + 1} integrations` : undefined,
    })),
];
